language: node_js
sudo: false
node_js:
- '0.12'
branches:
  only:
  - master
before_script:
- npm install -g jspm
- npm install -g protractor
- npm install -g karma-cli
- npm install -g divshot-cli
- webdriver-manager update
- jspm config registries.github.auth $JSPM_AUTH
- jspm install
script:
- divshot push development -t $DIVSHOT_AUTH
- jspm bundle app/bootstrap www/bundle/$(date +%s | sha256sum | base64 | head -c30;
  echo).js --inject --minify
- gulp build-index
- divshot push staging -t $DIVSHOT_AUTH
after_success:
- rm -rf www/app
- rm www/config.js
- divshot push production -t $DIVSHOT_AUTH
env:
  global:
  - secure: VmCZM38XiLVK9gSpqQPm+EDsp7xlUvv8mb01kc+Gm0k7nAc/GvdTXnTqfohv1PWGHlszD/T8kZ/UgfnamNFVvlAfrXkPlMCO2Fbn7+Y7JJh/gsRFl0UxELu1him0P5JdcWe3rh6kzxPrWOMQ8HXeod/Azd9uVa94aAMuwriz0E4=
  - secure: LsZhnDg7TZbh3Btxf8lmq1le/qVRjPYGEDdsXPE/ZIVa3ByIzND0rzdLwcWt0dfLhponcukLPLFimkgKz1IREo8AFq7CGRDUjlN2BTv207lu4ALBas7Ie7K/t7MHwZhGBkibktzqYSPJ+5T8tavY6TyfBeLc+2fqoGOmBMTV24JcxkwXcU70owT/v84Par+SyUIQj4qZTcWoaunEbT1FVHcWYdfOefz2qKCy7U9Z8LtBta87GEkdo97X6K1CB1zx5lnHQSiAaypJ2vqFLlPH65adYSFFlPWK8bWDGKxjtisvRsSAc+UdzufJDG9eAIukYR6I9E2JFrsgHMk8n42QAr/3M/Vt2cbQAVQJDUGeb9c9O4v3OAOcxjK2RsYgnDnFi53vBiB0dFsHyLBtWwDCO93MexC7AJTDnZUiYs1UM7FOk1+WPzpRfgswAgbdk5GNzzqag0ZCMtJpvEVBLlcogQ1fyAhNmL3dqcM8D8BgHnBlKUz6dQWkapgMLLj0KHT9MTvONQNGNU1sXTr+7sO1XQi54d0772sNATWyJXeGsXB+iv7ouUKFaxbroBiAVcj2oyOv8NTD5yYp11+bA1stj6vbtytPsh05ZRtcAJkqFpcvYmsZsfvEDOIGyO3uQCni9F2RJse6MBNDiQo8xLBnJ1GhM4buiJ7zm7me13F8a4I=
